name: Go Test

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Hack Code Climate and Go Modules
        if: github.event_name != 'pull_request'
        run: mkdir -p github.com/xuesea && ln -sf $(pwd) github.com/xuesea/goharbor-client

      - name: Test & publish code coverage
        if: github.event_name != 'pull_request'
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.codeClimateReporterID }}
        with:
          coverageCommand: go test -coverprofile=c.out ./...
          debug: true
          prefix: 'github.com/${{ github.repository }}/v5'

      - name: Go Test
        if: github.event_name == 'pull_request'
        run: go test -coverprofile=c.out ./...